WebApplication/Controllers/CurrentItineraryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Mvc;
using BryanAir.Contracts;
using Microsoft.AspNet.Identity;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    //ToDo: Kill off this bad idea... 
    public class CurrentItineraryController : Controller
    {
        public ActionResult CurrentItinerary()
        {
            if (User.Identity.IsAuthenticated)
            {
                var currentItineraryViewModel = ServiceClient.GetUserCurrentItinerary(User.Identity.GetUserId());
                return PartialView("_CurrentItinerary", currentItineraryViewModel);
            }
            
            return PartialView("_CurrentItinerary");
        }
    }
}

WebApplication/Controllers/ItineraryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    public class ItineraryController : Controller
    {
        


        [Authorize]
        public async Task<ActionResult> Index()
        {
            var userId = User.Identity.GetUserId();
            var itineraries = ServiceClient.GetUserItineraries(userId);
            return View(itineraries);
        }

        [Authorize]
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ItineraryViewModel itineraryViewModel = await ServiceClient.GetItineraryById((int) id);
            if (itineraryViewModel == null)
            {
                return HttpNotFound();
            }
            return View(itineraryViewModel);
        }

        [Authorize]
        public ActionResult Checkout(int id)
        {
            return RedirectToAction("Index", "Checkout", new {itineraryId = id});
        }

        [Authorize]
        public async Task<ActionResult> Cancel(int id)
        {
            var itinerary = await ServiceClient.GetItineraryById(id);
            var updated = await ServiceClient.UpdateItineraryStatusToCancelled(itinerary);

            if (!updated) ModelState.AddModelError("Badness", "We could not cancel your booking, you'll just have to go now.");

            var itineraries = ServiceClient.GetUserItineraries(User.Identity.GetUserId());
            ModelState.AddModelError("Goodness", "Booking Cancelled!");
            return View("Index", itineraries);
        }
    }
}

WebApplication/Views/Shared/_CurrentItinerary.cshtml
@model WebApplication.Models.ItineraryViewModel

<div>
    <h4>Itinerary</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

    </dl>
</div>
<p>
   @* @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")*@
</p>

WebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Bryan Air</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      @Html.ActionLink("Bryan Air", "Index", "Home", new {area = ""}, new {@class = "navbar-brand"})
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("My Itineraries", "Index", "Itinerary")</li>
        <li>@Html.ActionLink("Search", "Search", "Search")</li>
        <li>@Html.ActionLink("FlightAdmin", "Index", "FlightAdmin")</li>
      </ul>
      @Html.Partial("_LoginPartial")
    </div>
  </div>
</div>

  <div class="container body-content">
    
    @RenderBody()
    <hr/>
    <footer>
      <p>&copy; @DateTime.Now.Year - BryanAir Search App</p>
    </footer>
  </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>