WebApplication/Models/CheckoutViewModel.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Web;

namespace WebApplication.Models
{
    public class CheckoutViewModel
    {
/*        public int Id { get; set; }*/
        public UserParticularsViewModel UserParticularsViewModel { get; set; }
        public ItineraryViewModel ItineraryViewModel { get; set; }
        public int ItineraryId { get { return ItineraryViewModel.Id; } }

        public bool RequiresCreditCardInfo
        {
            get { return
                    (UserParticularsViewModel.CreditCardNumber == null
                    || UserParticularsViewModel.CreditCardExpirationDate == null); }
        }

        public decimal Total
        {
            get { return ItineraryViewModel.Bookings.Sum(b => (b.Price*b.TotalPassengers)); }
        }

        public string Tickets
        {
            get
            {
                // Not pretty, but build a giant ticket with all flights info make it pretty / partial view etc if time.

                var tickets = ItineraryViewModel.Bookings.Select(GetFlightTicket);
                return tickets.Aggregate((t1,t2) => t1 + " | " + t2);
            }
        }

        private string GetFlightTicket(BookingViewModel booking)
        {
            var flight = booking.Flight;
            return string.Format(CultureInfo.InvariantCulture, "{0}-{1}-{2}-{3}",
                flight.AirlineCode,
                flight.FlightNumber,
                // ToDo: Oops, login name is email ...use registered name, if null, use user GUID
                UserParticularsViewModel.Name ?? UserParticularsViewModel.ReferenceId.ToString(),
                UserParticularsViewModel.Id
                );
        }

    }
}

WebApplication/Models/UserParticularsViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.UI.WebControls;

namespace WebApplication.Models
{
    public class UserParticularsViewModel
    {
        [Key]
        public int Id { get; set; }

        [System.Web.Mvc.HiddenInput(DisplayValue = false)]
        public Guid ReferenceId { get; set; }

        [Required]
        public string Name { get; set; }
        
        [Required]
        [Display(Name = "Address Line 1")]
        public string AddressLine1 { get; set; }
        [Display(Name = "Address Line 2")]
        public string AddressLine2 { get; set; }
        
        [Required]
        public string Postcode { get; set; }
        
        [RegularExpression("([0-9\\s]+)", ErrorMessage = "Please enter a valid Card Number")]
        [StringLength(19, ErrorMessage = "The {0} must contain exactly {2} digits.", MinimumLength = 16)]
        [Display(Name = "Credit Card Number")]
        public string CreditCardNumber { get; set; } // 16 digits
        
        [RegularExpression("([0-9]?[0-9][0-9]?[0-9])", ErrorMessage = "Please enter a valid Expiration date format (mmyy)")]
        [Display(Name = "Credit Card Expiration Date (mm/yy)")]
        public string CreditCardExpirationDate { get; set; }
    }
}

WebApplication/Controllers/CheckoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using WebApplication.Models;
using System.Threading.Tasks;
using BryanAir.Contracts.Helpers;

namespace WebApplication.Controllers
{
    public class CheckoutController : Controller
    {
        // GET: Checkout
        [HttpGet]
        [Authorize]
        public async Task<ActionResult>Index(int itineraryId)
        {
            return View("Payment", await GetModel(itineraryId));
        }


        [HttpPost]
        [Authorize]
        public async Task<ActionResult> SaveParticulars([Bind(Include = "ItineraryId,UserParticularId,creditCardNumber,creditCardExpirationDate")] int itineraryId, string creditCardNumber, string creditCardExpirationDate, int userParticularId)
        {
            // By this point in the journey, a user particular must exist, so update credit card info only

            if  (!(creditCardNumber.Length > 0 && long.Parse(creditCardNumber)%int.Parse(creditCardExpirationDate) == 0))
                    ModelState.AddModelError("Badness", "A valid Credit Card number is divisable by it's expriation date.");

            if (ModelState.IsValid)
            {
                var isUpdateSuccessfull = await ServiceClient
                    .UpdateUserCreditcardParticulars(creditCardNumber, creditCardExpirationDate, User.Identity.GetUserId(), userParticularId);
             
                if (isUpdateSuccessfull)
                    return RedirectToAction("Index", new {itineraryId = itineraryId});
            }

            var model = await GetModel(itineraryId);
           
            ModelState.AddModelError("Badness", "Something bad has happened, it does, from time to time...so try again.");
            return View("Payment", model);

            
        }

        private async Task<CheckoutViewModel> GetModel(int itineraryId)
        {
            var itinerary = await ServiceClient.GetItineraryById(itineraryId);
            var userParticulars = ServiceClient.GetUserParticulars(User.Identity.GetUserId()) ?? new UserParticularsViewModel();
            return new CheckoutViewModel {ItineraryViewModel = itinerary, UserParticularsViewModel = userParticulars};
        }


        [HttpPost]
        [Authorize]
        public async Task<ActionResult> Pay(int itineraryId)
        {

            var itinerary = await ServiceClient.GetItineraryById(itineraryId);

            if (itinerary.Status == Status.Cancelled || itinerary.Status == Status.Booked)
            {
                ModelState.AddModelError("Badness", "This booking is already:" + itinerary.Status.ToString());
                return View("Payment", await GetModel(itineraryId));
            }

            var updated =  await ServiceClient.UpdateItineraryStatusToConfirmed(itinerary);

            if (!updated)
            {
                ModelState.AddModelError("Badness", "We could not take your money... but your money is important to us...try again.");
                return View("Payment", await GetModel(itineraryId));
            }

            ModelState.AddModelError("Goodness", "Booking Confirmed!");
            return View("Confirmation", await GetModel(itineraryId));

        }

       
    }
}

WebApplication/Views/Checkout/Confirmation.cshtml
@model WebApplication.Models.CheckoutViewModel

@{
    ViewBag.Title = "Confirmation";
}

<h2>Confirmation - Your Ticket</h2>

<div>
    <h4>Ticket</h4>
    <hr />
  <dl class="dl-horizontal">
  </dl>
  <dl>
    @Html.ValidationSummary("", new { @class = "text-success" })
    @Html.ValidationMessage("CustomError")
    @Html.DisplayFor(model => model.Tickets)
  </dl>
</div>
<p>

    @Html.ActionLink("Back to List", "Index")
</p>

WebApplication/Views/Checkout/Payment.cshtml
@model WebApplication.Models.CheckoutViewModel

@{
    ViewBag.Title = "Payment";
}

<h2>Payment</h2>



@using (Html.BeginForm(Model.RequiresCreditCardInfo ? "SaveParticulars" : "Pay", "Checkout", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <h4>CheckoutViewModel</h4>
        <hr />
        @Html.ValidationSummary("", new { @class = "text-danger" })
        @Html.ValidationMessage("CustomError")
        @Html.HiddenFor(model => model.ItineraryId)
        @Html.HiddenFor(e => e.UserParticularsViewModel.Id, new { @id = "UserParticularId", @Name = "UserParticularId" })
        

      Total Price: £ @Html.DisplayFor(model => model.Total)
      @{
        if (Model.RequiresCreditCardInfo)
        {
          Html.RenderPartial("_UserParticularsView", Model.UserParticularsViewModel);
        }
        
      }

      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          
          @{ var btnValue = Model.RequiresCreditCardInfo ? "Save" : "Pay";}
          <input type="submit" value=@btnValue class="btn btn-default"/>

        </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication/Views/Checkout/_UserParticularsView.cshtml
@using System.Web.Mvc.Html
@using System.Web.Optimization
@model WebApplication.Models.UserParticularsViewModel



    <div class="form-horizontal">
        <h4>Credit Card</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.CreditCardNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreditCardNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreditCardNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreditCardExpirationDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreditCardExpirationDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreditCardExpirationDate, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>